### PR TITLE
Add 'secret' to config schema

### PR DESCRIPTION
**Pull request by yakkomajuri**
Laying down the ground work for secret keys in plugins

### CODE REVIEW

**Review by Twixes — APPROVED** [review]
I like this solution.
We'll just have to first implement in the main repo too, so marking as draft for now.

**Review by mariusandra — APPROVED** [review]

**Comment by yakkomajuri** [comment]
Well the reason I made this is that I was giving this a quick look and to implement in the main repo I need this actually. Don't need _need_ but I get a TS error otherwise

**Comment by yakkomajuri** [comment]
@Twixes

**Comment by Twixes** [comment]
Hm, very well then.

**Pull request merged**
